//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace IFC.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class IFConsultingDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new IFConsultingDBEntities object using the connection string found in the 'IFConsultingDBEntities' section of the application configuration file.
        /// </summary>
        public IFConsultingDBEntities() : base("name=IFConsultingDBEntities", "IFConsultingDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IFConsultingDBEntities object.
        /// </summary>
        public IFConsultingDBEntities(string connectionString) : base(connectionString, "IFConsultingDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IFConsultingDBEntities object.
        /// </summary>
        public IFConsultingDBEntities(EntityConnection connection) : base(connection, "IFConsultingDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EmailSubscribe> EmailSubscribes
        {
            get
            {
                if ((_EmailSubscribes == null))
                {
                    _EmailSubscribes = base.CreateObjectSet<EmailSubscribe>("EmailSubscribes");
                }
                return _EmailSubscribes;
            }
        }
        private ObjectSet<EmailSubscribe> _EmailSubscribes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EmailSubscribes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmailSubscribes(EmailSubscribe emailSubscribe)
        {
            base.AddObject("EmailSubscribes", emailSubscribe);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IFConsultingDBModel", Name="EmailSubscribe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EmailSubscribe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EmailSubscribe object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static EmailSubscribe CreateEmailSubscribe(global::System.Int32 id, global::System.String email)
        {
            EmailSubscribe emailSubscribe = new EmailSubscribe();
            emailSubscribe.ID = id;
            emailSubscribe.Email = email;
            return emailSubscribe;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion
    
    }

    #endregion
    
}
